const projects = [
  {
    id: 1,
    imgLink: require('../img/project1.png'),
    title: "Resource Sharing Portal",
    description: "Resource sharing portal is a Web Application that provides a one-stop platform to the students for easy management of resources and course materials. It is a full-stack application implemented using the Django Framework.",
    stack: ["React", "NodeJs", "MongoDB", "Express", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/RSP",
    Link: "https://omanshu840.github.io/RSP/",
  },
  {
    id: 2,
    imgLink: require('../img/project2.png'),
    title: "O-Meets: A Video Calling Platform",
    description: "A Web Application that facilitates video conferencing by implementing WebRtc architecture(Peer to Peer) with dynamic chat room support. NodeJs framework is used in the implementation.",
    stack: ["NodeJs", "Express", "WebRTC", "Socket.io", "JavaScript","HTML", "CSS"],
    githubLink: "https://github.com/Omanshu840/Video-Calling-Platform",
    Link: "https://o-meets.onrender.com/",
  },
  {
    id: 6,
    imgLink: require('../img/project6.png'),
    title: "Socio-Engage: Social Media Web App",
    description: "A social media Web Application built in MERN stack. It supports various functionalities, including User Authentication,  Creating Posts, Following existing users.",
    stack: ["NodeJs", "React", "MongoDB", "Express", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/Socio-Engage",
    Link: "https://omanshu840.github.io/Socio-Engage/",
  },
  {
    id: 9,
    imgLink: require('../img/project9.png'),
    title: "Explitter",
    description: "An app to quickly split and calculate bills among a group with precise shares. The app is build using Reach Javascript library which uses Redux for state management.",
    stack: ["React", "Redux", "JavaScript", "HTML", "CSS"],
    githubLink: "https://github.com/Omanshu840/Expense-Splitter",
    Link: "https://omanshu840.github.io/Expense-Splitter/"
  },
  {
    id: 10,
    imgLink: require('../img/project10.png'),
    title: "Tab Maker",
    description: "An app to create and maintain guitar tabs. The app is build using Reach Javascript library which uses Redux for state management.",
    stack: ["React", "Redux", "JavaScript", "HTML", "CSS"],
    githubLink: "https://github.com/Omanshu840/Tab-Maker",
    Link: "https://omanshu840.github.io/Tab-Maker/"
  },
  {
    id: 10,
    imgLink: require('../img/project11.png'),
    title: "Trip Plan",
    description: "An app to quickly access and maintain trip plan. The app is build using Reach Javascript library.",
    stack: ["React", "JavaScript", "HTML", "CSS"],
    githubLink: "https://github.com/Omanshu840/Trip-Plan",
    Link: "https://omanshu840.github.io/Trip-Plan/"
  },
  {
    id: 7,
    imgLink: require('../img/project7.png'),
    title: "Mysuru Tourism Website",
    description: "Mysuru Tourism Web Application was built for the DSCWOW Hackathon organized by the Developer Students Club. It focuses on the travelers visiting Mysuru and provides them a brief guide of Mysuru tourism. The Application was built using the ReactJs frontend library with Firebase serving as the cloud database.",
    stack: ["React", "Firebase", "Dialogflow", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/DSCWOW_DeltaG_Mysuru_Tourism",
    Link: "https://mysuru-tourism.herokuapp.com/",
  },
  {
    id: 3,
    imgLink: require('../img/project3.png'),
    title: "Facial Expression Based Movie Recommender",
    description: "A Web Application that recommends movies by analyzing the facial expressions of the user. I worked on CNN Model with Keras and Backend of the Web Application with Flask Framework.",
    stack: ["Python", "Keras", "Flask", "HTML", "CSS", "MySQL"],
    githubLink: "https://github.com/Omanshu840/Movie-Recommender",
    Link: "https://www.youtube.com/watch?v=n9FIgEeSloE",
  },
  {
    id: 4,
    imgLink: require('../img/project4.png'),
    title: "Long Document Classification using BERT",
    description: "Implemented Hierarchical Transformers for classification of Long documents using Natural Language Processing, Bidirectional Encoder Representations from Transformers to achieve an accuracy of 89.88% on 20 newsgroup long articles containing 250 words or more. Implemented and trained Recurrence over BERT model on the Spam Assassin dataset to build a Spam Classifier.",
    stack: ["Python", "PyTorch", "Transformers"],
    githubLink: "https://github.com/Omanshu840/Long-Document-Classification-using-BERT",
    Link: "https://youtu.be/ZhU9pwrZHMU",
  },
  {
    id: 5,
    imgLink: require('../img/project5.png'),
    title: "OS Simulator",
    description: "A Web Application that simulates various activities executed by the Operating System. I worked on UI/UX design and the Back-end of the application with the Django Framework.",
    stack: ["Python", "Django", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/OS-Simulator",
    Link: "https://os-sim.herokuapp.com",
  },
  {
    id: 8,
    imgLink: require('../img/project8.png'),
    title: "Extraction of Crop Cycle Parameters",
    description: "A Web Application that implements an algorithm to extract the crop cycle parameters for a given set of multispectral multi-temporal data. It was built for the Smart India Hackathon 2020.",
    stack: ["Python", "Flask", "OpenCV", "HTML", "CSS"],
    githubLink: "https://github.com/SIH-NITK/Hex-Clan",
    Link: "https://github.com/Omanshu840/SIH2020_Internal",
  },
]

export default projects;